site_name: FiveOrbs Boiler
copyright: © 2022-2024 ebene fünf GmbH
nav:
  - 'Introduction': index.md
  - quickstart.md
  - engine.md
  - rendering.md
  - values.md
  - layouts.md
  - inserts.md
  - sections.md
  - template.md
theme:
    name: fiveorbs
repo_url: https://github.com/fiveorbs/boiler
extra:
    project: Boiler
plugins:
    - search
    - macros:
        module_name: docs/main
