name: Docs

# on:
#   push:
#     tags:
#       - '*'
on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run markdownlint
        uses: articulate/actions-markdownlint@v1
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-vacantplanet
      - run: mkdocs gh-deploy --force
